# Generated by Django 3.2 on 2021-05-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopGainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('last', models.FloatField()),
                ('prev', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TopLoser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('last', models.FloatField()),
                ('prev', models.FloatField()),
            ],
        ),
    ]
